---
kind: ReplicationController
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: k8s.gcr.io/guestbook:v3
        ports:
        - name: http-server
          containerPort: 3000
        volumeMounts:
        # name must match the volume name below
        - name: myvolume
          mountPath: "/tmp/volume"
      volumes:
        - name: myvolume
          persistentVolumeClaim:
            claimName: test-pv-claim


